---@alias NotNil
---| string
---| number
---| table
---| boolean
---| function
---| userdata
---| thread

--- @class ThemeAwareStyle : vim.api.keyset.highlight
--- Whether the style adapts automatically to the current theme.
--- @field theme_aware? boolean

--- Unique identifier of a component.
--- @alias CompId string

--- References other components for resolving dynamic fields.
---@class Reference
---@field events? CompId|CompId[]
---@field timing? CompId|CompId[]
---@field hidden? CompId|CompId[]
---@field style? CompId
---@field left? CompId
---@field left_style? CompId
---@field right? CompId
---@field right_style? CompId
---@field [string] CompId


--- @alias PaddingFunc fun(self: ManagedComponent, session: Session): integer|PaddingTable
--- @alias PaddingTable {left: integer|nil|PaddingFunc, right:integer|nil|PaddingFunc}
---
--- @alias UpdateFunc fun(self: ManagedComponent, session: Session): nil|string, nil|CompStyle
---
--- @alias CompStyle ThemeAwareStyle|string
---
--- @alias StyleFunc fun(self: ManagedComponent, session: Session): CompStyle
--- @alias SideStyleFunc fun(self: ManagedComponent, session: Session): CompStyle|SepStyle
---
--- @alias OnClickMouseButton "l"|"r"|"m"
--- @alias OnClickModifier "s"|"c"|"a"|"m"
--- @alias OnClickFunc fun(self: ManagedComponent, minwid: 0, click_times: number, mouse_button: OnClickMouseButton, modifier_pressed: OnClickModifier)
--- @alias OnClickTable {callback: OnClickFunc|string, name: string|nil}


--- @class Component
--- @field [integer] Component A table of child components, can be used to create a list of components
---
--- @field id? CompId Unique identifier of the component.
---
--- Controls how often the component is updated.
--- - `true`: update once per second.
--- - `integer`: update every *n* timer ticks.
--- @field timing? boolean|integer
---
--- Whether initialization is deferred until the component is first used.
--- @field lazy? boolean
---
--- Whether the component can be rendered as a standalone component.
--- @field renderable? boolean
---
--- Called once when the component is created.
--- Use this to configure or modify the component before initialization.
---@field constructor? fun(comp: Component)
---
--- User-configurable values.
--- @field config? table
---
--- The priority of the component when the status line is too long, higher numbers are more likely to be truncated.
--- @field flexible? number
---
--- A function to determine whether the component should be automatically adjusted to suit the theme.
--- @field theme_aware? boolean|fun(self: ManagedComponent, session: Session): boolean
---
--- A flag indicating whether the component should show individual value for each window.
--- @field win_individual? boolean
---
--- A table of events that the component will listen to.
---
--- Inline syntax (strings only): `<Event> [<Pat>[,<Pat>...]] [++once]`
---
---   `"ModeChanged"`                             — event only
---   `"BufEnter *.lua"`                          — event + pattern
---   `"BufEnter *.lua,*.py"`                     — event + multiple patterns
---   `"BufEnter ++once"`                         — event + fire once
---   `"BufEnter *.lua ++once"`                   — event + pattern + once
---   `"User VeryLazy"`                           — User event name as pattern
---   `"User VeryLazy ++once"`                    — User event + once
---   `{ "BufEnter", "BufEnter *.lua ++once" }`   — array of event strings
--- @field events? string|string[]
---
--- A table of references to other components that this component depends on
--- @field delegator? Reference
---
--- Style for the left separator.
--- - string: highlight group name.
--- - table: highlight properties (e.g. `{fg = "#fff", bold = true}`).
--- - SepStyle: SepFg/SepBg/Reverse/Inherited.
--- - function(self, ctx): called and return value used as above.
--- @field left_style? CompStyle|SideStyleFunc|SepStyle
---
--- Left separator text.
--- - string: used as is.
--- - function(self, ctx): called and return value used.
--- @field left? string|UpdateFunc
---
--- Style for the right separator.
--- - string: highlight group name.
--- - table: highlight properties.
--- - SepStyle: SepFg/SepBg/Reverse/Inherited.
--- - function(self, ctx): called and return value used as above.
--- @field right_style? CompStyle|SideStyleFunc|SepStyle
---
--- Right separator text.
--- - string: used as is.
--- - function(self, ctx): called and return value used.
--- @field right? string|UpdateFunc
---
--- Padding around the component.
--- - integer: spaces on both sides (default 1 if nil).
--- - table: `{left = n, right = n}` per side, each defaults to 0 if nil.
---   - Each field can also be a function(self, session) returning a number.
--- - function(self, session): return integer or table as above.
--- @field padding? integer|PaddingTable|PaddingFunc
---
--- An initialization function that will be called when the component is first loaded.
--- @field init? fun(self: ManagedComponent)
---
--- Component style.
--- - string: highlight group name.
--- - table: highlight properties (e.g. `{fg = "#fff", bold = true}`).
--- - nil: no style applied.
--- - function(self, session): called and return value used as above.
--- @field style? CompStyle|StyleFunc
---
--- A function that will be called before the component is updated.
--- @field pre_update? fun(self: ManagedComponent, session: Session)
---
--- Update function to get the component value.
--- - string: used as is.
--- - nil: component not updated.
--- - function(self, session): return value is the component text, optionally return a second value for style.
--- @field update? string|UpdateFunc
---
--- A function that will be called after the component is updated.
--- @field post_update? fun(self: ManagedComponent, session: Session)
---
--- Called to check if the component should be displayed, should return true or false
--- - If nil: the component is always shown.
--- - If function: called and its return value is used to determine if the component should be visible.
--- @field hidden? fun(self: ManagedComponent, session: Session): boolean|nil
---
---
--- Click handler for the component.
--- - nil: not clickable.
--- - string: name of a global function.
--- - function(self, minwid, click_times, mouse_button, modifier_pressed).
--- - table: `{callback = func|string, name = string|nil}`.
--- @field on_click? string|OnClickFunc|OnClickTable
---
--- @private
--- @field ___loaded? boolean Component has been initialized.
--- @field ___hidden? boolean Cached visibility state.
--- @field ___parent_id? CompId The id of the container component.
--- @field ___accept_returned_style? boolean Whether the style returned by `update()` should override `style`
---
--- @field ___resolved_hl_name? string Highlight group used for the main content.
--- @field ___left_hl_name? string Highlight group used for the left separator.
--- @field ___right_hl_name? string Highlight group used for the right separator.
--- @field ___click_handler? string Registered click handler name.


--- @class DefaultComponent : Component
--- @field [integer] DefaultComponent A table of child components, can be used to create a list of components
--- @field id DefaultId the id of default component
--- @field ___builtin true Mark as created by witch-line

--- @class ManagedComponent : DefaultComponent | Component
--- @field [integer] ManagedComponent A table of child components, can be used to create a list of components
--- @field id CompId the id of component
--- @field ___loaded true Always `true` for managed components.
--- @field ___parent_id CompId The id of the container component.


---@alias LiteralComponent string

---@alias CombinedComponent
---| CombinedComponent[]
---| DefaultId
---| LiteralComponent
---| DefaultComponent
---| Component
---| ManagedComponent
