return {
    mode = require("witch-line.components.builtin.mode"),
    file = require("witch-line.components.builtin.file"),
    git = require("witch-line.components.builtin.git"),
    diagnostic = require("witch-line.components.builtin.diagnostic"),
    cursor = require("witch-line.components.builtin.cursor"),
    lsp = require("witch-line.components.builtin.lsp"),
    encoding = require("witch-line.components.builtin.encoding"),
    datetime = require("witch-line.components.builtin.datetime"),
    battery = require("witch-line.components.builtin.battery"),
    spell = require("witch-line.components.builtin.spell"),
    macro = require("witch-line.components.builtin.macro"),
    search = require("witch-line.components.builtin.search"),
    selection = require("witch-line.components.builtin.selection"),
    indent = require("witch-line.components.builtin.indent"),
    nvim_dap = require("witch-line.components.builtin.nvim_dap"),
    os_uname = require("witch-line.components.builtin.os_uname"),
    copilot = require("witch-line.components.builtin.ai.copilot"),
    codeium = require("witch-line.components.builtin.ai.codeium.codeium"),
    neocodeium = require("witch-line.components.builtin.ai.codeium.neocodeium"),
}
